// Auto-generated map: category title -> public image URL (served from plr-members/public).
export const CATEGORY_IMAGES: Record<string, string> = {
  "Canva Templates": "/category-images/canva-templates.webp",
  "Notion Templates": "/category-images/notion-templates.webp",
  "eBooks": "/category-images/ebooks.webp",
  "DFY Courses": "/category-images/dfy-courses.webp",
  "Journals & Planners": "/category-images/journals-and-planners.webp",
  "Social Media Templates": "/category-images/social-media-templates.webp",
  "Logo Templates": "/category-images/logo-templates.webp",
  "PowerPoint Templates": "/category-images/powerpoint-templates.webp",
  "Fonts": "/category-images/fonts.webp",
  "Icons": "/category-images/icons.webp",
  "AI Graphics": "/category-images/ai-graphics.webp",
  "Reels & Shorts": "/category-images/reels-and-shorts.webp",
  "Royalty-Free Images": "/category-images/royalty-free-images.webp",
  "Royalty-Free Videos": "/category-images/royalty-free-videos.webp",
  "Royalty-Free Audio": "/category-images/royalty-free-audio.webp",
  "Lightroom Presets": "/category-images/lightroom-presets.webp",
  "Photoshop Actions": "/category-images/photoshop-actions.webp",
  "Photoshop Brushes": "/category-images/photoshop-brushes.webp",
  "Photoshop Overlays": "/category-images/photoshop-overlays.webp",
  "Photoshop Presets": "/category-images/photoshop-presets.webp",
  "Illustrator Assets": "/category-images/illustrator-assets.webp",
  "SVG Assets": "/category-images/svg-assets.webp",
  "Editable Infographics": "/category-images/editable-infographics.webp",
  "Excel Templates": "/category-images/excel-templates.webp",
  "Resume Templates": "/category-images/resume-templates.webp",
  "Brochures & Flyers": "/category-images/brochures-and-flyers.webp",
  "Business & Legal Templates": "/category-images/business-and-legal-templates.webp",
  "SOP Templates": "/category-images/sop-templates.webp",
  "Business Database": "/category-images/business-database.webp",
  "Printable Wall Art": "/category-images/printable-wall-art.webp",
  "Frame Artwork": "/category-images/frame-artwork.webp",
  "Coloring Books": "/category-images/coloring-books.webp",
  "Die-Cut Stickers": "/category-images/die-cut-stickers.webp",
  "T-Shirt & Mug Designs": "/category-images/t-shirt-and-mug-designs.webp",
  "Mobile App Templates": "/category-images/mobile-app-templates.webp",
  "WordPress Templates": "/category-images/wordpress-templates.webp",
  "Video Editing Assets": "/category-images/video-editing-assets.webp",
  "Niche Articles": "/category-images/niche-articles.webp",
  "AI Prompts Bundle": "/category-images/ai-prompts-bundle.webp",
  "Faceless Guides": "/category-images/faceless-guides.webp",
  "Carousel Bundle": "/category-images/carousel-bundle.webp",
  "Bio Link Bundle": "/category-images/bio-link-bundle.webp",
  "Influencers Bundle": "/category-images/influencers-bundle.webp",
  "Mega Gym Bundle": "/category-images/mega-gym-bundle.webp",
  "Restaurants Bundle": "/category-images/restaurants-bundle.webp",
  "CyberPunk Collection": "/category-images/cyberpunk-collection.webp",
  "CorelDraw Templates": "/category-images/coreldraw-templates.webp",
  "Canva Mockups": "/category-images/canva-mockups.webp"
}
